# These are supported funding model platforms

github: [trapexit] # [user]
patreon: trapexit
open_collective: trapexit
ko_fi: trapexit
custom: ['https://www.subscribestar.com/trapexit','https://paypal.me/trapexit']
