language: cpp

matrix:
  include:
    - os: linux
      dist: precise
      compiler: gcc
      sudo: required
    - os: linux
      dist: precise
      compiler: clang
      sudo: required
    - os: linux
      dist: trusty
      compiler: gcc
      sudo: required
    - os: linux
      dist: trusty
      compiler: clang
      sudo: required
    - os: osx
      compiler: clang

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/cask; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install osxfuse; fi

script:
  - sudo -E make install-build-pkgs
  - make
